# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_pupub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pupub_date',
            new_name='pub_date',
        ),
    ]
